app1/urls.py
from app1.views import *
from django.urls import path


app_name='nishi'
urlpatterns = [
     path('nishi/',nishi,name='nishi')
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='tap'
urlpatterns=[
     path('tapan/',tapan,name='tapan')
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def nishi(request):
     return render(request, 'nishi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def tapan(request):
     return render(request, 'tapan.html')

templates/nishi.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
</head>
<body>
     <center>
          <h1>Nishi is python student </h1>
          <p>Santosh sir is teaching us</p>
          <a href="{% url 'tap:tapan' %}">Sntosh sir </a>
     </center>
</body>
</html>

templates/tapan.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
</head>
<body>
     <center>
          <h1>Tapan from Odisha</h1>
          <p>he is from kendrapara district ,pin-754217</p>
          <h2><a href="{% url 'nishi:nishi' %}">pattamundai.......</a></h2>
          
          
     </center>
</body>
</html>